### ISSUE TITLE
Export of PHA needed

### ISSUE THREAD

**Issue by kristinsj** [radcampaign/pension-help#3]
> I hope everyone is doing well.  You may have seen that, at long last, in January the Pension Rights Center finally launched its new wordpress website for [pensionrights.org](http://pensionrights.org/) (so the old Drupal 6 website is gone).  
> I am writing today to ask about pulling some data from [PensionHelp America](http://www.pensionhelp.org); In previous years, the web team that managed PHA was able to export PHA content (agencies, locations, plans) into an Excel worksheet for me.  The reason for the export - it allowed me to do a mail merge to send out update requests to the various service providers in PensionHelp America.  Do you see an easy way to export the service provider data into an Excel document that I could use?  I have attached an example of what these exports looked like in previous years.
> Kyle
https://radcampaign.basecamphq.com/projects/14490095-pension-help/posts/113311288/comments

**Comment by jselt** [comment]
is that spreadsheet all he needs?

**Comment by kristinsj** [comment]
That's how I read it. We can do that, correct?

**Comment by jselt** [comment]
Yeah we can do it from the DB - just wasn't clear if there were more
exports he needed or not,  Like of different categories, not that I even
remember what those are :)
<http://www.radcampaign.com/>

*Jared Seltzer, PARTNER*
[office] 202/290-2218 <2022902218>
[mobile] 240/353-4894 <2403534894>
[email] ***@***.*** ***@***.***>

*www.RadCampaign.com <http://www.radcampaign.com/>*
***@***.*** <http://twitter.com/#!/RadCampaign>
[addr.] 1627 Conn. Ave., NW Ste. 2
Washington, DC 20009 <http://g.co/maps/j22r>

"Take eloquence and wring its neck."

**Comment by kristinsj** [comment]
sorry, still not grasping what the followup question is. you need to know if he wants something other than all the service provider data?

**Comment by jselt** [comment]
Yes. Sorry
<http://www.radcampaign.com/>

*Jared Seltzer, PARTNER*
[office] 202/290-2218 <2022902218>
[mobile] 240/353-4894 <2403534894>
[email] ***@***.*** ***@***.***>

*www.RadCampaign.com <http://www.radcampaign.com/>*
***@***.*** <http://twitter.com/#!/RadCampaign>
[addr.] 1627 Conn. Ave., NW Ste. 2
Washington, DC 20009 <http://g.co/maps/j22r>

"Take eloquence and wring its neck."

**Comment by kristinsj** [comment]
thanks - sorry i'm super dense after today

**Comment by jselt** [comment]
No no -  I wasn't particularly coherent

**Comment by kristinsj** [comment]
I added this to the Sprint Backlog. Is it doable today/Monday?

**Comment by jselt** [comment]
I put in a 5 hour estimate cause I literally have no idea how long this will take - anywhere from 1 to 5, so I was going to push this a bit - I could try on Monday if we want to get it out of the way.

Otherwise maybe later next week?

**Comment by kristinsj** [comment]
later is fine with me - just let Kyle know we'll get to it next week

**Comment by jselt** [comment]
[query_result_2022-03-07T20_14_01.333Z.xlsx](https://github.com/radcampaign/pension-help/files/8200563/query_result_2022-03-07T20_14_01.333Z.xlsx)

Here's a spreadsheet. I think the one he sent was filtered - but I don't know on what so...I also added this to the Dashboard of the Pension Help Reports site so he can grab it whenever needed. https://pha-reports.herokuapp.com/dashboard/1 - it's called Agency Export

**Comment by kristinsj** [comment]
Awesome thanks!

**Comment by jselt** [comment]
Oops - thought the addresses were in there already. Attached

[query_result_2022-03-07T21_43_01.591Z.xlsx](https://github.com/radcampaign/pension-help/files/8201061/query_result_2022-03-07T21_43_01.591Z.xlsx)

**Comment by jselt** [comment]
Ugh - this database is so poorly thought out - I'll look at it more tomorrow.

**Comment by jselt** [comment]
[query_result_2022-03-08T15_51_24.928Z.xlsx](https://github.com/radcampaign/pension-help/files/8207633/query_result_2022-03-08T15_51_24.928Z.xlsx)

Ok - this definitely has a lot of different addresses :)
