### ISSUE TITLE
Google Analytics 4 setup for PensionHelp.Org

### ISSUE THREAD

**Issue by kristinsj** [radcampaign/pension-help#7]
> As you may know, Google Analytics is changing how data is tracked for web traffic.  Universaly Analytics is being phased out for Google Analytics 4 starting in July of this year.  Can I use whatever support hours PRC has for your help in getting the Google Analytics 4 account set up so that PHA web traffic can continue to be tracked?  I think it requires that a Google Tag be set up on the PHA website.

Asked for access via info@rad:
https://radcampaign.basecamphq.com/projects/14490095-pension-help/posts/114517019/comments

**Comment by kristinsj** [comment]
@jselt do you have time to look at this one? They set up something, so I think just need to add it to the website.

**Comment by jselt** [comment]
Added the code - will check back to see if data is coming in

**Comment by jselt** [comment]
Data coming into GA - all set I guess.

**Comment by kristinsj** [comment]
Thanks! Relayed.
